package com.example.prakashreddy45.project;

/**
 * Created by Prakash Reddy 45 on 9/26/2016.
 */
public class ClientID {
    String[] client_id={"dhe09\n",
            "dhe10\n",
            "dhe11\n",
            "dhe12\n",
            "dhe13\n",

            "san12\n",
            "san13\n",
            "san14\n",
            "san15\n",
            
                    "dh1\n" ,
                    "dh2\n" ,
                    "dh3\n" ,
                    "dh4\n" ,
                    "dh5\n" ,
                    "dh6\n" ,
                    "dh7\n" ,
                    "dh8\n" ,
                    "dh9\n" ,
                    "dh10\n" ,
                    "dh11\n" ,
                    "dh12\n" ,
                    "dh13\n" ,
                    "dh14\n" ,
                    "dh15\n" ,
                    "dh16\n" ,
                    "dh17\n" ,
                    "dh18\n" ,
                    "dh19\n" ,
                    "dh20\n" ,
                    "dh21\n" ,
                    "dh22\n" ,
                    "dh23\n" ,
                    "dh24\n" ,
                    "dh25\n" ,
                    "dh26\n" ,
                    "dh27\n" ,
                    "dh28\n" ,
                    "dh29\n" ,
                    "dh30\n" ,
                    "dh31\n" ,
                    "dh32\n" ,
                    "dh33\n" ,
                    "dh34\n" ,
                    "dh35\n" ,
                    "dh36\n" ,
                    "dh37\n" ,
                    "dh38\n" ,
                    "dh39\n" ,
                    "dh40\n" ,
                    "dh41\n" ,
                    "dh42\n" ,
                    "dh43\n" ,
                    "dh44\n" ,
                    "dh45\n" ,
                    "dh46\n" ,
                    "dh47\n" ,
                    "dh48\n" ,
                    "dh49\n" ,
                    "dh50\n" ,
                    "dh51\n" ,
                    "dh52\n" ,
                    "dh53\n" ,
                    "dh54\n" ,
                    "dh55\n" ,
                    "dh56\n" ,
                    "dh57\n" ,
                    "dh58\n" ,
                    "dh59\n" ,
                    "dh60\n" ,
                    "dh61\n" ,
                    "dh62\n" ,
                    "dh63\n" ,
                    "dh64\n" ,
                    "dh65\n" ,
                    "dh66\n" ,
                    "dh67\n" ,
                    "dh68\n" ,
                    "dh69\n" ,
                    "dh70\n" ,
                    "dh71\n" ,
                    "dh72\n" ,
                    "dh73\n" ,
                    "dh74\n" ,
                    "dh75\n" ,
                    "dh76\n" ,
                    "dh77\n" ,
                    "dh78\n" ,
                    "dh79\n" ,
                    "dh80\n" ,
                    "dh81\n" ,
                    "dh82\n" ,
                    "dh83\n" ,
                    "dh84\n" ,
                    "dh85\n" ,
                    "dh86\n" ,
                    "dh87"
    };
}
